// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    BorderTrack: typeof import('./src/components/BorderTrack.vue')['default']
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LedStrip: typeof import('./src/components/LedStrip.vue')['default']
    LightOrchestra: typeof import('./src/components/LightOrchestra.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Old: typeof import('./src/components/Old.vue')['default']
    Plasma: typeof import('./src/components/Plasma.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Simulator: typeof import('./src/components/Simulator.vue')['default']
    Strip: typeof import('./src/components/Strip.vue')['default']
    StripConfigurator: typeof import('./src/components/StripConfigurator.vue')['default']
  }
}
